// Normally generated by `wrangler types`. Hand-written here since this
// project has no other bindings yet.
interface Env {
  FETCH_MCP: DurableObjectNamespace;
  // Set with `wrangler secret put MCP_SHARED_SECRET` (or .dev.vars locally).
  MCP_SHARED_SECRET: string;
}
